Repository julia-vscode/julia-vscode, pull requests merged in 2018-12, with the labels that each got.

#625 Fix sendText call on Windows
  src/repl.ts
Labels: bug

#624 Fix a julia environment selector UI bug
  src/jlpkgenv.ts
Labels: bug

#626 Make sure backslash in F5 runs are ok
  src/repl.ts
Labels: bug

#643 Fix VegaLite and add PlotlyJS
  libs/plotly/plotly.min.js
  libs/vega-lite/vega-embed.min.js
  libs/vega-lite/vega-lite.min.js
  libs/vega-lite/vega.min.js
  scripts/terminalserver/terminalserver.jl
  src/repl.ts
Labels: bug, enhancement

#641 Preserve webview panel column
  src/repl.ts
Labels: enhancement

#644 Release keyboard bindings after plot pane is closed
  src/repl.ts
Labels: bug
