Repository julia-vscode/julia-vscode, pull requests merged in 2019-06, with the labels that each got.

#739 Add test task that outputs coverage
  scripts/tasks/task_test.jl
  src/tasks.ts
Labels: enhancement

#740 Open docs after build task
  src/tasks.ts
Labels: enhancement

#741 Make sure docs build uses current package version
  src/tasks.ts
Labels: bug

#743 Run doc build on temp copy of Project.toml from docs
  scripts/tasks/task_docbuild.jl
  src/tasks.ts
Labels: enhancement

#747 Fix code loading
  scripts/languageserver/main.jl
  scripts/languageserver/packages/Manifest.toml
  scripts/languageserver/packages/Project.toml
  src/extension.ts
Labels: bug

#754 Fix JULIA_EDITOR path on mac
  src/repl.ts
Labels: bug

#755 Make sure all background in weave preview is white
  scripts/weave/preview.tpl
Labels: area-weave, bug

#757 Fix executeCode for single line case
  src/repl.ts
Labels: bug

#759 Add highlighting for several languages embedded as strings
  package.json
  syntaxes/julia.json
Labels: enhancement

#761 Support for custom sysimg
  package.json
  scripts/tasks/task_compileenv.jl
  src/jlpkgenv.ts
  src/repl.ts
  src/tasks.ts
Labels: enhancement

#763 Copy latest syntax from Atom
  syntaxes/julia.json
Labels: bug

#766 Adds automatic transformation of atom-language-julia grammar.
  package.json
  syntaxes/julia.json
  syntaxes/juliacodeblock.json
  syntaxes/juliamarkdown.json
  syntaxes/update_syntax.jl
Labels: bug, enhancement

#773 Fix error reporting for multi line error messages
  scripts/languageserver/main.jl
  src/telemetry.ts
Labels: bug

#777 Add cell-wise evaluation.
  package.json
  src/repl.ts
Labels: area-code-execution, enhancement
