Repository julia-vscode/julia-vscode, pull requests merged in 2019-05, with the labels that each got.

#719 additional julia command line args
  package.json
  src/repl.ts
Labels: enhancement

#720 Streamline communication with REPL
  scripts/terminalserver/terminalserver.jl
  src/repl.ts
Labels: enhancement

#722 Auto detect julia 1.1.1 and 1.2.0
  src/juliaexepath.ts
Labels: enhancement

#723 Return from startREPL once all sockets are started
  scripts/terminalserver/terminalserver.jl
  src/repl.ts
Labels: area-repl, bug

#712 add delete all plots
  package.json
  src/repl.ts
Labels: area-plotpane, enhancement

#690 Use environment from current working directory
  src/jlpkgenv.ts
Labels: enhancement

#724 Add new execution model
  scripts/terminalserver/repl.jl
  scripts/terminalserver/terminalserver.jl
  src/repl.ts
Labels: area-code-execution, enhancement

#727 Preserve focus when plot pane is shown
  src/repl.ts
Labels: area-plotpane, enhancement

#729 Add environmentPath configuration setting
  package.json
  src/jlpkgenv.ts
Labels: area-environments, enhancement

#726 Grid view
  libs/ag-grid/LICENSE.txt
  libs/ag-grid/ag-grid-community.min.noStyle.js
  libs/ag-grid/ag-grid.css
  libs/ag-grid/ag-theme-balham.css
  scripts/terminalserver/terminalserver.jl
  src/repl.ts
Labels: area-gridpane, enhancement

#730 Fix a julia 1.0 compat bug
  src/jlpkgenv.ts
Labels: area-environments, bug

#735 Have julia tasks use active julia env
  src/tasks.ts
Labels: area-environments, enhancement

#736 Use WebView for weave
  src/weave.ts
Labels: area-weave, bug
