Repository julia-vscode/julia-vscode, pull requests merged in 2020-11, with the labels that each got.

#1741 pass Ctrl-C to REPL when not evaling
  package.json
  src/interactive/repl.ts
Labels: bug

#1759 Add support for Julia 1.5.4
  src/juliaexepath.ts
Labels: enhancement

#1762 switch to unbuffered channels for eval
  scripts/packages/VSCodeServer/src/eval.jl
Labels: bug

#1760 improve LS startup interaction with inline eval
  src/extension.ts
  src/interactive/modules.ts
  src/interactive/repl.ts
  src/jlpkgenv.ts
Labels: internal

#1779 allow string arg in executeFile
  src/interactive/repl.ts
Labels: enhancement
