Repository julia-vscode/julia-vscode, pull requests merged in 2020-09, with the labels that each got.

#1644 Show error msg if both insider and regular installed
  src/extension.ts
Labels: enhancement

#1665 softscope on Julia >=1.5
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/repl.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  src/interactive/repl.ts
Labels: area-code-execution

#1516 update the module status bar item correctly
  src/interactive/modules.ts
Labels: bug
