Repository julia-vscode/julia-vscode, pull requests merged in 2020-04, with the labels that each got.

#1109 Properly load base files in debugger
  scripts/debugger/debugger_requests.jl
  scripts/debugger/debugger_utils.jl
Labels: area-debugger, bug

#1110 Fix drilldown into structs when value undef
  scripts/debugger/debugger_requests.jl
Labels: area-debugger, bug

#1111 Make sure include works during debug
  scripts/debugger/debugger_requests.jl
Labels: area-debugger, bug

#1098 Fix a wrong config name
  src/smallcommands.ts
Labels: area-ls-linter, bug

#1114 Use imports instead of require
  package-lock.json
  package.json
  src/jlpkgenv.ts
  src/juliaDebug.ts
  src/juliaexepath.ts
  src/packagepath.ts
Labels: enhancement

#1107 Make telemetry language more precise
  src/extension.ts
  src/telemetry.ts
Labels: enhancement

#1117 Hide dep warnings for LS process
  src/extension.ts
Labels: bug

#1119 Update list of julia versions we search for
  src/juliaexepath.ts
Labels: enhancement

#1104 Prioritize JULIA_NUM_THREADS if it exists
  .vscode/launch.json
  package.json
  src/repl.ts
  src/test/suite/utils.test.ts
  src/utils.ts
Labels: area-code-execution, enhancement

#1123 Use webpack for the extension
  .gitignore
  .vscode/launch.json
  .vscodeignore
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#1126 Update README
  README-insider.md
  README.md
Labels: enhancement

#1131 Fix the launch config
  .vscode/launch.json
Labels: bug

#1130 Fix a bug in the numThreads config
  src/tasks.ts
Labels: bug

#1146 Use our own exception type for precompile failures
  scripts/languageserver/main.jl
Labels: enhancement

#1125 Update grammar
  syntaxes/julia.json
Labels: enhancement

#1128 Echo Julia code in REPL before executing it
  scripts/terminalserver/terminalserver.jl
Labels: area-code-execution, enhancement

#1155 Validate a position
  src/repl.ts
Labels: area-code-execution, bug

#1157 Remove deprecated config notification registration
  src/extension.ts
Labels: bug
