Repository julia-vscode/julia-vscode, pull requests merged in 2020-08, with the labels that each got.

#1536 Tweak pipeline definition
  azure-pipelines.yml
Labels: enhancement

#1555 new way to load Revise
  scripts/terminalserver/terminalserver.jl
Labels: enhancement

#1553 don't leak internals into ARGS
  scripts/terminalserver/terminalserver.jl
  src/interactive/repl.ts
Labels: bug

#1570 Add crash reporting to activate function
  src/extension.ts
Labels: bug

#1515 fix up connection/module handling:
  src/interactive/modules.ts
Labels: bug

#1574 invokelatest in showingrid_notification
  scripts/packages/VSCodeServer/src/display.jl
Labels: area-gridpane, bug

#1580 package server setting
  package.json
  src/extension.ts
  src/interactive/repl.ts
Labels: enhancement

#1594 add stopREPL command
  package.json
  src/interactive/repl.ts
Labels: enhancement

#1604 Changed activity bar from filled to outline
  images/julia-dots-outline.svg
  package.json
Labels: enhancement

#1478 enable run/debug julia file via commands
  package.json
  src/debugger/debugFeature.ts
Labels: bug, enhancement

#1630 Add Julia 1.5.1 & 1.5.2 and remove 1.4.3
  src/juliaexepath.ts
Labels: enhancement
