Repository julia-vscode/julia-vscode, pull requests merged in 2020-07, with the labels that each got.

#1435 re-fix display_error bug
  scripts/packages/VSCodeServer/src/eval.jl
Labels: bug

#1433 more and improved error tracing
  src/extension.ts
  src/interactive/modules.ts
  src/telemetry.ts
Labels: enhancement

#1442 add extension api
  src/extension.ts
Labels: enhancement

#1444 setup environement for developement
  .vscode/settings.json
  scripts/environments/development/Manifest.toml
  scripts/environments/development/Project.toml
  src/extension.ts
Labels: internal

#1445 Some strict improvements
  src/tasks.ts
  src/utils.ts
Labels: enhancement

#1448 update development environment in updateDeps
  scripts/environments/development/Manifest.toml
  src/scripts/updateDeps.ts
Labels: internal

#1449 More simplifications for doc browser
  package.json
  src/interactive/documentation.ts
Labels: enhancement

#1450 fix undef handling in workspace
  scripts/packages/VSCodeServer/src/trees.jl
Labels: bug

#1451 rendering improvement
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/misc.jl
  src/interactive/results.ts
Labels: enhancement

#1424 improve result interaction
  package.json
  src/interactive/results.ts
  src/utils.ts
Labels: enhancement

#1453 Add run and debug button and move code around
  package.json
  src/debugger/debugFeature.ts
  src/extension.ts
Labels: enhancement

#1454 stop using Ctrl+J prefix
  package.json
Labels: bug

#1452 add disabledDirs config
  package.json
Labels: area-ls-linter

#1470 Put the run and debug button in proper nav group
  package.json
Labels: enhancement

#1464 Update CHANGELOG for v0.17
  CHANGELOG.md
Labels: enhancement

#1475 Fix a getModuleForEditor race condition
  src/interactive/repl.ts
Labels: bug

#1476 Wrap a call to user code in a try catch
  scripts/packages/VSCodeServer/src/eval.jl
Labels: bug

#1477 Add ChromeProfileFormat to updateDeps.ts and CI
  azure-pipelines.yml
  scripts/testenvironments/chromeprofileformat/Manifest.toml
  scripts/testenvironments/chromeprofileformat/Project.toml
  src/scripts/updateDeps.ts
Labels: enhancement

#1482 more isrepl checks
  scripts/packages/VSCodeServer/src/repl.jl
Labels: area-code-execution, bug

#1472 Handle errors in julia binary search
  package-lock.json
  package.json
  src/juliaexepath.ts
Labels: bug

#1481 Fix error handling
  scripts/packages/VSCodeServer/src/eval.jl
Labels: area-code-execution, bug

#1496 Fix another getModuleForEditor race condition
  src/interactive/modules.ts
  src/interactive/repl.ts
Labels: bug

#1498 Remove Revise load warning
  scripts/terminalserver/terminalserver.jl
Labels: bug

#1505 quick fix for #1500
  src/interactive/repl.ts
Labels: bug

#1499 Change default for missingrefs to none
  package.json
Labels: bug

#1511 Fix a world age error and handle faulty show methods
  scripts/packages/VSCodeServer/src/eval.jl
Labels: bug

#1534 Publish to openvsx
  azure-pipelines.yml
Labels: enhancement
