Repository julia-vscode/julia-vscode, pull requests merged in 2020-06, with the labels that each got.

#1264 Add different cloudRole properties to crash reports
  scripts/debugger/run_debugger.jl
  scripts/error_handler.jl
  scripts/languageserver/main.jl
  scripts/terminalserver/terminalserver.jl
  src/extension.ts
  src/telemetry.ts
Labels: enhancement

#1267 Add npm task for installing all dependencies after a fresh clone
  package.json
Labels: enhancement

#1270 Update Readme (add install Julia)
  README.md
Labels: enhancement

#1274 Remove duplicate g_terminal.show calls
  src/interactive/repl.ts
Labels: enhancement

#1272 Tweak title for a command
  package.json
Labels: enhancement

#1273 Remove a duplicate def of TextDocumentPositionParams
  src/interactive/misc.ts
  src/interactive/modules.ts
  src/interactive/repl.ts
Labels: enhancement

#1003 Add support for the Julia workspace view
  images/julia-dots.svg
  package.json
  scripts/terminalserver/repl.jl
  scripts/terminalserver/terminalserver.jl
  src/interactive/repl.ts
  src/interactive/workspace.ts
Labels: enhancement

#1288 follow up #1003
  scripts/terminalserver/terminalserver.jl
Labels: enhancement

#1295 "Julia REPL" as terminal name
  src/interactive/repl.ts
Labels: enhancement

#1296 improve render/strlimit etc
  scripts/terminalserver/misc.jl
  scripts/terminalserver/terminalserver.jl
Labels: enhancement, internal

#1262 introduce eslint
  .eslintignore
  .eslintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/extension.ts
  src/interactive/modules.ts
  src/interactive/plots.ts
  src/interactive/repl.ts
  src/interactive/results.ts
  src/interactive/workspace.ts
  src/jlpkgenv.ts
  src/juliaDebug.ts
  src/juliaexepath.ts
  src/openpackagedirectory.ts
  src/packagepath.ts
  src/scripts/updateDeps.ts
  src/settings.ts
  src/smallcommands.ts
  src/tasks.ts
  src/telemetry.ts
  src/test/runTest.ts
  src/test/suite/extension.test.ts
  src/test/suite/index.ts
  src/test/suite/utils.test.ts
  src/utils.ts
  src/weave.ts
  tsconfig.json
Labels: internal

#1305 Update recommended extensions
  .vscode/extensions.json
Labels: enhancement

#1311 fix toplevel statements in repl eval
  scripts/terminalserver/terminalserver.jl
Labels: bug

#1319 package up vscodeserver
  .vscode/launch.json
  scripts/debugger/debugger.jl
  scripts/vscodeserver/Project.toml
  scripts/vscodeserver/boot_repl.jl
  scripts/vscodeserver/src/gridviewer.jl
  scripts/vscodeserver/src/misc.jl
  scripts/vscodeserver/src/repl.jl
  scripts/vscodeserver/src/trees.jl
  scripts/vscodeserver/src/vscodeserver.jl
  src/interactive/repl.ts
Labels: enhancement

#1321 Move vscodeserver
  azure-pipelines.yml
  scripts/debugger/debugger.jl
  scripts/packages/VSCodeServer/Project.toml
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/gridviewer.jl
  scripts/packages/VSCodeServer/src/misc.jl
  scripts/packages/VSCodeServer/src/repl.jl
  scripts/packages/VSCodeServer/src/trees.jl
  scripts/packages/VSCodeServer/test/runtests.jl
  scripts/terminalserver/terminalserver.jl
  src/interactive/repl.ts
Labels: bug

#1329 fix repl again
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/repl.jl
Labels: area-repl, bug

#1252 Add github issue notebooks
  .vscodeignore
  projectmanagement/releases.github-issues
  projectmanagement/todo.github-issues
Labels: enhancement

#1320 Update for DocumentFormat config changes
  package.json
Labels: Showstopper

#1336 more careful LS startup:
  src/extension.ts
Labels: bug

#1333 Add telemetry for invalid positions
  src/extension.ts
  src/telemetry.ts
Labels: bug

#1340 Mark julia.executablePath as machine-overridable
  package.json
Labels: bug

#1356 use vscode-builtin icons
  media/delete-inverse.svg
  media/delete.svg
  media/next-inverse.svg
  media/next.svg
  media/previous-inverse.svg
  media/previous.svg
  package.json
Labels: enhancement

#1350 Use JSONRPC msg dispatcher for REPL
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  src/interactive/repl.ts
  src/interactive/workspace.ts
Labels: enhancement

#1355 change execution path correctly:
  src/extension.ts
  src/interactive/repl.ts
  src/jlpkgenv.ts
  src/juliaexepath.ts
  src/openpackagedirectory.ts
  src/packagepath.ts
  src/settings.ts
  src/smallcommands.ts
  src/tasks.ts
  src/telemetry.ts
  src/weave.ts
Labels: bug

#1363 Further split VSCodeServer into individual files
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/debug_cmds.jl
  scripts/packages/VSCodeServer/src/display.jl
  scripts/packages/VSCodeServer/src/misc.jl
  scripts/packages/VSCodeServer/src/module.jl
  scripts/packages/VSCodeServer/src/render.jl
  scripts/packages/VSCodeServer/src/request_handlers.jl
Labels: enhancement

#1353 fix ws for zero-dim arrays
  scripts/packages/VSCodeServer/src/request_handlers.jl
  scripts/packages/VSCodeServer/src/trees.jl
Labels: bug

#1370 stop inline eval from force-showing the REPL
  src/interactive/repl.ts
Labels: area-code-execution, enhancement

#1371 reorganize functions more
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/debugger.jl
  scripts/packages/VSCodeServer/src/display.jl
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/module.jl
  scripts/packages/VSCodeServer/src/render.jl
  scripts/packages/VSCodeServer/src/trees.jl
Labels: internal

#1375 Add two Project.toml files so that things precompile
  scripts/packages/DebugAdapter/Project.toml
  scripts/packages/VSCodeDebugger/Project.toml
Labels: enhancement

#1387 better inline result background color
  src/interactive/results.ts
Labels: enhancement

#1341 highlight stackframe on inline evaluation error
  scripts/packages/VSCodeServer/Project.toml
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/misc.jl
  scripts/packages/VSCodeServer/src/repl.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  src/interactive/repl.ts
  src/interactive/results.ts
Labels: area-code-execution, enhancement, juno-parity

#1395 improve repl/LS startup error handling
  src/interactive/repl.ts
Labels: area-code-execution, bug

#1253 Add Julia 1.5 support
  azure-pipelines.yml
  src/juliaexepath.ts
Labels: enhancement

#1405 Fix a number of precompile warnings for the debugger
  scripts/packages/VSCodeDebugger/Project.toml
Labels: Showstopper, area-debugger, bug

#1403 fix WS tableview
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  scripts/packages/VSCodeServer/src/trees.jl
Labels: bug

#1406 make sure to show errors when evaling file
  scripts/packages/VSCodeServer/src/eval.jl
  src/interactive/repl.ts
Labels: bug

#1409 Run more tests as part of our CI
  .vscodeignore
  azure-pipelines.yml
  scripts/packages/VSCodeDebugger/test/runtests.jl
  scripts/packages/VSCodeServer/Project.toml
  scripts/testenvironments/debugadapter/Manifest.toml
  scripts/testenvironments/debugadapter/Project.toml
  scripts/testenvironments/vscodedebugger/Manifest.toml
  scripts/testenvironments/vscodedebugger/Project.toml
  scripts/testenvironments/vscodeserver/Manifest.toml
  scripts/testenvironments/vscodeserver/Project.toml
  src/scripts/updateDeps.ts
Labels: enhancement

#1425 minor improvements
  src/interactive/results.ts
Labels: enhancement

#1429 Replace isnothing with comparison
  scripts/packages/VSCodeServer/src/misc.jl
Labels: bug

#1423 check docversion in module/blockrange requests
  src/interactive/misc.ts
  src/interactive/modules.ts
  src/interactive/repl.ts
Labels: bug

#1431 fix display_error(stderr, err, nothing) call
  scripts/packages/VSCodeServer/src/eval.jl
Labels: area-code-execution, bug

#1432 stepInTargets support
  src/debugger/debugProtocol.ts
  src/debugger/juliaDebug.ts
Labels: area-debugger, enhancement
