Repository julia-vscode/julia-vscode, pull requests merged in 2020-05, with the labels that each got.

#1159 Moves the symbol store out of the extension path
  scripts/languageserver/main.jl
  src/extension.ts
Labels: enhancement

#1166 Adjust debug mode for LS
  scripts/languageserver/main.jl
Labels: bug

#1120 Crash reporting for the debugger
  scripts/debugger/debugger.jl
  scripts/debugger/launch_wrapper.jl
  scripts/debugger/run_debugger.jl
  scripts/error_handler.jl
  scripts/languageserver/main.jl
  scripts/terminalserver/terminalserver.jl
  src/extension.ts
  src/juliaDebug.ts
  src/repl.ts
  src/telemetry.ts
Labels: area-debugger, enhancement

#1173 Fix a typo
  scripts/languageserver/main.jl
Labels: bug

#1172 update julia config options
  package.json
Labels: enhancement

#1177 Fix a bug in REPLTree
  src/repl.ts
Labels: bug

#1186 Use a version of findfirst that exists on all Julia versions
  scripts/debugger/debugger_rcp.jl
  scripts/debugger/debugger_requests.jl
Labels: bug

#1188 Strongly type the appinsights object
  package-lock.json
  package.json
  src/telemetry.ts
Labels: enhancement

#1209 Properly fix a bug
  scripts/debugger/debugger.jl
  scripts/debugger/debugger_rcp.jl
  scripts/debugger/debugger_requests.jl
Labels: area-debugger, bug

#1208 Remove dead code from REPL
  scripts/terminalserver/terminalserver.jl
Labels: enhancement

#1213 Adopt VS Code's 'asWebviewUri' API
  src/repl.ts
Labels: bug

#1214 Always pass JULIA_NUM_THREADS to repl
  src/repl.ts
Labels: bug

#1215 Increase git.detectSubmodulesLimit to 20
  .vscode/settings.json
Labels: enhancement

#1216 Remove Toggle File Linting
  package.json
  src/smallcommands.ts
Labels: bug

#1220 Integrate JSONRPC with tools
  azure-pipelines.yml
  src/scripts/updateDeps.ts
Labels: enhancement

#1231 split repl.ts into multiple files
  src/extension.ts
  src/interactive/plots.ts
  src/interactive/repl.ts
  src/interactive/workspace.ts
  src/juliaDebug.ts
Labels: area-code-execution, enhancement

#1234 Remove dead command
  package.json
  src/smallcommands.ts
Labels: bug

#1187 Handle empty file case in debugger
  scripts/debugger/debugger_requests.jl
Labels: area-debugger, bug

#1238 Add Julia 1.4.3 to the list of versions
  src/juliaexepath.ts
Labels: enhancement

#1239 Remove a dead request handler
  src/extension.ts
Labels: enhancement

#1241 Add a status bar item for LS startup
  src/extension.ts
Labels: enhancement

#1249 refactor: listen for onSetLanguageClient, onDidChangeConfig event
  src/extension.ts
  src/interactive/repl.ts
  src/jlpkgenv.ts
  src/juliaexepath.ts
  src/openpackagedirectory.ts
  src/packagepath.ts
  src/smallcommands.ts
  src/tasks.ts
  src/telemetry.ts
  src/weave.ts
Labels: enhancement, internal

#1251 Formatting
  .vscode/settings.json
  scripts/debugger/debugger.jl
  scripts/debugger/debugger_core.jl
  scripts/debugger/debugger_rcp.jl
  scripts/debugger/debugger_requests.jl
  scripts/debugger/debugger_utils.jl
  scripts/debugger/launch_wrapper.jl
  scripts/error_handler.jl
  scripts/languageserver/main.jl
  scripts/tasks/task_compileenv.jl
  scripts/tasks/task_docbuild.jl
  scripts/tasks/task_test.jl
  scripts/terminalserver/repl.jl
  scripts/terminalserver/terminalserver.jl
  scripts/weave/run_weave.jl
  src/extension.ts
  src/interactive/plots.ts
  src/interactive/repl.ts
  src/jlpkgenv.ts
  src/juliaDebug.ts
  src/juliaexepath.ts
  src/openpackagedirectory.ts
  src/packagepath.ts
  src/scripts/updateDeps.ts
  src/settings.ts
  src/smallcommands.ts
  src/tasks.ts
  src/telemetry.ts
  src/utils.ts
  src/weave.ts
  syntaxes/update_syntax.jl
Labels: enhancement, internal

#1258 Rearrange code and add support for vector and matrix to grid
  scripts/terminalserver/gridviewer.jl
  scripts/terminalserver/terminalserver.jl
Labels: enhancement

#1261 Fix how we handle unsupported types for vscodedisplay
  scripts/terminalserver/terminalserver.jl
Labels: Showstopper, bug

#1259 improve cell delimiter regex
  CHANGELOG.md
  src/interactive/repl.ts
Labels: area-code-execution, enhancement

#1263 update ignore settings
  .gitignore
  .vscode/settings.json
Labels: internal
