Repository julia-vscode/julia-vscode, pull requests merged in 2021-05, with the labels that each got.

#2142 fix error stack display
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/repl.jl
Labels: area-code-execution

#2144 Make package tagging Julia 1.6 only and improve update script
  scripts/packagedev/tagnewpackageversion.jl
  src/scripts/updateDeps.ts
Labels: bug

#2155 no-debug terminal name change to "Julia Session"
  src/debugger/juliaDebug.ts
Labels: area-debugger, enhancement

#2121 add "inline, error in REPL" option
  package.json
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  src/interactive/repl.ts
Labels: enhancement

#1963 Add config options for new completions modes (ver 2)
  CHANGELOG.md
  package.json
Labels: enhancement

#2028 Update symbol store version to v5
  scripts/languageserver/main.jl
Labels: enhancement

#1893 support persistent tmux sessions
  package.json
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  src/interactive/repl.ts
Labels: enhancement

#1932 WIP: Add a plot panel for switching plots
  libs/html2canvas/html2canvas.min.js
  libs/plotter/plotter.css
  libs/plotter/plotter.scss
  package.json
  src/interactive/plots.ts
  src/interactive/plots/main_plot_webview.js
  src/interactive/plots/panel_webview.js
Labels: enhancement

#2161 add terminal link handler for julia specific link syntax
  src/interactive/repl.ts
  src/interactive/results.ts
  src/juliaexepath.ts
Labels: enhancement

#2174 plot navigator fixes
  package.json
  src/docbrowser/documentation.ts
  src/interactive/plots.ts
Labels: area-plotpane

#2182 improvements to tmux/external process workflow
  CHANGELOG.md
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/repl.jl
  src/interactive/repl.ts
Labels: bug
