Repository julia-vscode/julia-vscode, pull requests merged in 2021-02, with the labels that each got.

#1902 Disable live testing
  src/tasks.ts
Labels: bug

#1903 Fix some corner cases of env handling
  src/extension.ts
  src/jlpkgenv.ts
Labels: bug

#1905 Allow persistance of relative env paths
  src/debugger/debugFeature.ts
  src/extension.ts
  src/interactive/repl.ts
  src/jlpkgenv.ts
  src/tasks.ts
Labels: bug

#1898 Add a cancel token to getModuleAt story
  src/interactive/modules.ts
Labels: bug

#1911 Update plotly
  libs/plotly/plotly.min.js
  scripts/packages/VSCodeServer/src/display.jl
  src/interactive/plots.ts
Labels: bug

#1918 Add support for Julia 1.6
  azure-pipelines.yml
  src/juliaexepath.ts
Labels: enhancement

#1933 only show explorer context menu entries when REPL is running
  package.json
  src/interactive/repl.ts
Labels: enhancement

#1939 fix svg display regression
  CHANGELOG.md
  src/interactive/plots.ts
Labels: area-plotpane

#1959 use repl ast transforms on 1.5 and up
  scripts/packages/VSCodeServer/src/repl.jl
Labels: area-code-execution, bug

#1957 unparametrize wrapper
  scripts/packages/VSCodeServer/src/eval.jl
Labels: bug

#1968 more robust repl hook setup
  scripts/packages/VSCodeServer/src/repl.jl
Labels: bug

#1970 fix search zindex in docpane
  src/docbrowser/documentation.ts
Labels: bug

#1973 fix typo in repl init code
  scripts/packages/VSCodeServer/src/repl.jl
Labels: bug
