Repository julia-vscode/julia-vscode, pull requests merged in 2021-06, with the labels that each got.

#2200 fix plot asset loading in bundle
  scripts/plots/main_plot_webview.js
  scripts/plots/panel_webview.js
  src/interactive/plots.ts
Labels: area-plotpane

#2053 Search all julia versions and display in the kernel picker
  src/juliaexepath.ts
  src/notebook/notebookKernel.ts
Labels: area-notebook

#980 Add notebook controller implementation
  package-lock.json
  package.json
  scripts/notebook/notebook.jl
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/notebookdisplay.jl
  scripts/packages/VSCodeServer/src/serve_notebook.jl
  scripts/packages/VSCodeServer/src/stdio.jl
  src/extension.ts
  src/interactive/repl.ts
  src/interactive/workspace.ts
  src/juliaexepath.ts
  src/notebook/helpers.ts
  src/notebook/notebookFeature.ts
  src/notebook/notebookKernel.ts
Labels: enhancement

#2251 Fix Windows search paths
  src/juliaexepath.ts
Labels: Showstopper, bug

#2252 Detect notebook Julia environments
  src/notebook/notebookKernel.ts
Labels: area-notebook, enhancement
