Repository julia-vscode/julia-vscode, pull requests merged in 2021-11, with the labels that each got.

#1507 dynamic completions and signature helps
  package.json
  scripts/environments/development/Manifest.toml
  scripts/packages/VSCodeServer/Project.toml
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/completions.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  src/interactive/completions.ts
  src/interactive/repl.ts
Labels: enhancement, discussion

#2415 Overhaul table viewer
  CHANGELOG.md
  libs/ag-grid/ag-grid-balham-dark.css
  libs/ag-grid/ag-grid-balham.css
  libs/ag-grid/ag-grid-community.min.noStyle.js
  libs/ag-grid/ag-grid.css
  libs/ag-grid/ag-grid.js
  libs/ag-grid/ag-theme-balham.css
  package.json
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/display.jl
  scripts/packages/VSCodeServer/src/gridviewer.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  scripts/packages/VSCodeServer/src/tables/filtering.jl
  scripts/packages/VSCodeServer/src/tables/tableviewer.jl
  src/interactive/plots.ts
  src/interactive/tables.ts
Labels: enhancement, area-gridpane

#2296 Overhaul keybindings
  package.json
Labels: enhancement
