Repository julia-vscode/julia-vscode, pull requests merged in 2021-01, with the labels that each got.

#1852 fix code insiders binary name on macos
  src/interactive/repl.ts
Labels: bug

#1676 Improve telemetry dialogues
  src/extension.ts
  src/telemetry.ts
Labels: enhancement

#1863 Move LS depot to globalStoragePath
  scripts/languageserver/julia_pkgdir/.gitignore
  src/extension.ts
Labels: enhancement

#1865 Fix a race condition
  src/interactive/modules.ts
Labels: bug

#1870 Add support for tagging package versions
  package.json
  scripts/environments/pkgdev/Manifest.toml
  scripts/environments/pkgdev/Project.toml
  scripts/packagedev/tagnewpackageversion.jl
  src/extension.ts
  src/packagedevtools.ts
Labels: enhancement

#1873 Add option for live test file
  package.json
  scripts/packages/VSCodeLiveUnitTesting/src/VSCodeLiveUnitTesting.jl
  scripts/tasks/task_liveunittesting.jl
  src/tasks.ts
Labels: enhancement

#1876 Update node packages
  package-lock.json
  package.json
  src/debugger/debugProtocol.ts
  src/debugger/juliaDebug.ts
  src/extension.ts
  src/interactive/modules.ts
  src/interactive/repl.ts
  src/interactive/workspace.ts
  src/jlpkgenv.ts
  src/test/suite/index.ts
Labels: bug

#1883 Replace all uses of single arg JSON RPC types
  scripts/packages/VSCodeServer/src/debugger.jl
  scripts/packages/VSCodeServer/src/display.jl
  scripts/packages/VSCodeServer/src/misc.jl
  scripts/packages/VSCodeServer/src/module.jl
  scripts/packages/VSCodeServer/src/profiler.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  scripts/packages/VSCodeServer/src/trees.jl
  scripts/terminalserver/terminalserver.jl
  src/debugger/debugProtocol.ts
  src/debugger/juliaDebug.ts
  src/docbrowser/documentation.ts
  src/interactive/modules.ts
  src/interactive/profiler.ts
  src/interactive/repl.ts
  src/interactive/workspace.ts
  src/jlpkgenv.ts
Labels: Showstopper, bug

#1886 Set path for live testing properly
  scripts/packages/VSCodeLiveUnitTesting/src/VSCodeLiveUnitTesting.jl
Labels: bug

#1887 fix profile notification
  scripts/packages/VSCodeServer/src/repl_protocol.jl
Labels: bug

#1896 Fix for #1895 Benchmark task MethodError
  src/tasks.ts
Labels: bug
