Repository julia-vscode/julia-vscode, pull requests merged in 2021-09, with the labels that each got.

#2419 Dispose REPLNode in workspace
  src/interactive/workspace.ts
Labels: bug, area-repl

#2394 Revert #2371
  package.json
  src/juliaexepath.ts
  src/tasks.ts
Labels: bug

#2379 Change executablePath scope to machine-override
  package.json
Labels: enhancement

#2402 Add executeInREPL to API
  src/extension.ts
  src/interactive/repl.ts
Labels: enhancement

#2273 Interactive (zoomable/pannable) Plots
  CHANGELOG.md
  libs/svg-pan-zoom/svg-pan-zoom.min.js
  package.json
  scripts/plots/main_plot_webview.js
  src/interactive/plots.ts
  src/scripts/updateDeps.ts
Labels: enhancement, area-plotpane

#2346 Commands/button to toggle plot pane status
  package.json
  src/interactive/plots.ts
Labels: enhancement, area-plotpane

#2329 Extensible diagnostics display
  package.json
  scripts/packages/VSCodeServer/src/VSCodeServer.jl
  scripts/packages/VSCodeServer/src/display.jl
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/repl_protocol.jl
  src/interactive/repl.ts
  src/interactive/results.ts
Labels: enhancement

#2428 Properly deduplicate the cachedJuliaExePaths
  src/juliaexepath.ts
Labels: area-notebook

#2431 executeActiveFile runs editor content
  package.json
  src/interactive/repl.ts
Labels: enhancement, area-code-execution

#2437 focus existing REPL in startREPLCommand
  src/interactive/repl.ts
Labels: bug

#2442 Fix svg plotting
  src/interactive/plots.ts
Labels: bug, area-plotpane

#2443 Fix typo to re-enable zoom for vega plots
  src/interactive/plots.ts
Labels: bug, area-plotpane

#2424 Save metadata in jupyter notebooks
  package.json
  src/notebook/notebookFeature.ts
Labels: bug, area-notebook

#2450 restrict plot pan/zoom to alt/option key
  scripts/plots/main_plot_webview.js
  src/interactive/plots.ts
Labels: bug, area-plotpane
