Repository julia-vscode/julia-vscode, pull requests merged in 2021-08, with the labels that each got.

#2336 Tweak settings.json
  .vscode/settings.json
Labels: enhancement

#2342 Fix some strict typing bugs
  src/debugger/debugFeature.ts
  src/debugger/juliaDebug.ts
  src/interactive/results.ts
  src/packagedevtools.ts
Labels: bug

#2341 Rewrite Julia executable search code
  package-lock.json
  package.json
  src/debugger/debugFeature.ts
  src/debugger/juliaDebug.ts
  src/extension.ts
  src/interactive/repl.ts
  src/jlpkgenv.ts
  src/juliaexepath.ts
  src/notebook/notebookFeature.ts
  src/notebook/notebookKernel.ts
  src/packagedevtools.ts
  src/packagepath.ts
  src/scripts/updateDeps.ts
  src/tasks.ts
  src/weave.ts
Labels: enhancement

#2347 Revise.revise for notebook eval
  scripts/packages/VSCodeServer/src/eval.jl
  scripts/packages/VSCodeServer/src/misc.jl
  scripts/packages/VSCodeServer/src/serve_notebook.jl
Labels: bug, area-notebook

#2348 Use normal function syntax for gotoFrame
  src/interactive/results.ts
Labels: bug

#2364 Fix Julia exe search
  src/extension.ts
  src/jlpkgenv.ts
  src/juliaexepath.ts
  src/utils.ts
Labels: Showstopper

#2371 Use a hack to fix a tasks problem with juliaup
  src/juliaexepath.ts
  src/tasks.ts
Labels: Showstopper

#2382 fix gridviewer ambiguity
  scripts/packages/VSCodeServer/src/gridviewer.jl
Labels: bug, area-gridpane

#2372 split getDefaultEnvPath execFile args
  src/jlpkgenv.ts
Labels: bug

#2395 Fix arg passing to Julia
  src/jlpkgenv.ts
  src/juliaexepath.ts
  src/packagepath.ts
Labels: Showstopper

#2362 Fix image-like size to always fit pane
  src/interactive/plots.ts
Labels: bug, area-plotpane

#2376 update plotly version to 2.3.1
  libs/plotly/plotly.min.js
Labels: enhancement, area-plotpane
