Repository julia-vscode/julia-vscode, pull requests merged in 2022-04, with the labels that each got.

#2817 Telemetry improvements
  src/telemetry.ts
Labels: bug

#2776 Use glob pattern for workspaceContains activation
  package.json
Labels: enhancement

#2825 Capitalize task source properly
  src/tasks.ts
Labels: bug

#2828 Fix a notebook bug
  src/notebook/notebookKernel.ts
Labels: bug, area-notebook

#2830 Fix a readonly problem
  src/notebook/notebookKernel.ts
Labels: bug, area-notebook

#1509 create 'Julia: New Julia File' command
  package.json
  src/smallcommands.ts
Labels: enhancement
