Repository julia-vscode/julia-vscode, pull requests merged in 2022-03, with the labels that each got.

#2778 Readd development env and fix updateDeps.ts
  scripts/environments/development/Manifest.toml
  scripts/environments/development/Project.toml
  src/scripts/updateDeps.ts
Labels: bug

#2779 Add Julia version check for tagging feature
  src/packagedevtools.ts
Labels: bug

#2781 Catch display errors in notebook exec
  scripts/packages/VSCodeServer/src/serve_notebook.jl
Labels: bug, area-notebook

#2782 Fix a world age bug in revise() call
  scripts/packages/VSCodeServer/src/misc.jl
Labels: bug, area-notebook

#2783 Make error handling in notebooks more robust
  scripts/packages/VSCodeServer/src/serve_notebook.jl
Labels: bug, area-notebook

#2790 Remove LS middleware
  src/extension.ts
Labels: enhancement

#2796 Improve juliaup integration with LS
  src/extension.ts
  src/juliaexepath.ts
Labels: bug

#2798 Fix a bug that relative deved packages aren't found
  src/jlpkgenv.ts
Labels: bug

#2791 Add source map support for exceptions
  package-lock.json
  package.json
  src/extension.ts
Labels: enhancement

#2804 Show error message first in crash report
  scripts/error_handler.jl
Labels: enhancement

#2801 Fix various REPL bugs
  src/interactive/repl.ts
Labels: bug

#2803 Fix a bug in notebook error handling
  scripts/packages/VSCodeServer/src/serve_notebook.jl
Labels: bug, area-notebook

#2807 Fix/persistent killed on reload
  src/interactive/repl.ts
Labels: bug, area-code-execution
